# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9634af4efc649297e9ee14b79aa053f9da1c2949f51d489426aaf9f22758931d6acb7de34e95865e596b10174949a450ed33ef4c4c26807e5fa62ebd5be4d85

test:
  secret_key_base: e9e5ca8b22636d2bd9a9b5ac74086c4cc00ba9e2a74667f7a16d11d804f80a52114e90f0f019c86b428e8d388a85678ea77c1a6cac7f9b95e44d830b9392b8fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
